### PR TITLE
Code generator & generated ids files

### PR DESCRIPTION
**Pull request by aiseeq**
My PR can make more questions than solving problems. Maybe I should need to take another names for packages. And I don't know how to solve problem when AbilityId (and others) should be uint32. I think we should use type Ability uint32, but it means, that we should rework many *.pb.go files. Also I'm not entirely sure that I'm importing abilities ids right.

### CODE REVIEW

**Comment by grantmd** [comment]
Oh, this is really neat. So there's a json file somewhere that this reads and generates named constants for all the abilites and units and such? That's way better than hard-coding the numeric IDs, like I had been doing.

Yes, getting types to cooperate with the types in the generated protobuf files may be an issue. Perhaps when we write new wrappers around the protobuf stuff we can stick to the types in the generated constants (since we control those). They could then cast as appropriate before calling into protobuf land. It's also possible that we could specify the types when generating the Go protobuf files, though it's been a while since I've looked into how that works. I kind of doubt it though. We should not hand-edit those generated files though.

I think this is mergeable as-is. Good next step for making the rest of the thing into more of a library than a one-trick monolith pony.

**Comment by grantmd** [comment]
Although I would move all the generated `*.go` files up a level, and the generator into another top-level directory like `scripts/` unless I'm missing a reason why you put them each in their own directories.

**Comment by aiseeq** [comment]
Yes, there is a reason. You just can't put 2 .go files with "package main" and "func main()" in one directory. Go executable could only be made from package main and func main() - only possible entry point. And you can't put files from different packages into the same folder. So, I see only one good way to organize project. If I want to use unit.Factory and ability.Attack, they should be in different packages, thus in different folders. And any executable should have it's own folder. So, I put everything in folder sc2ids, because they related. If you can imagine something better, It would be good.

**Comment by grantmd** [comment]
Oh right, of course. We will probably move things around some, but the whole project needs a re-org so we can do that at the same time. Thank you!

**Pull request merged**
